### ISSUE TITLE
Does it work with TypeScript JSX?

### ISSUE THREAD

**Issue by gianpaj** [1nVitr0/plugin-vscode-invert-if#27]
I'm getting
```
No invert condition provider found for this file type
```

It's a `.tsx` file
Language mode: `TypeScript JSX`

<img width="1227" alt="image" src="https://github.com/1nVitr0/plugin-vscode-invert-if/assets/899175/a7f1710f-94a2-431e-b3a4-5ebe2f36ea4d">

**Comment by 1nVitr0** [comment]
@gianpaj Sorry for the late response. Currently the extension uses `acorn` for parsing `JavaScript` and `TypeScript`. Unfortunately this does not support `Jsx` / `tsx` out of the box. I have been looking into other methods (such as using the internal ts-language server, but have not gotten anywhere yet. I might rework the included language supports, though it will probably not be this year.

**Comment by 1nVitr0** [comment]
Looking into it, it will definitely take a rework of the typescript / javascript extension. It will take a few weeks for me to come to a more robust approach and the implement that.

**Comment by 1nVitr0** [comment]
@gianpaj Sorry, it took me a while. It should now be working, though I'll have to update all the tests to verify completely. Let me know if there is any configuration where it is not
